In [296]:
# Exercise 1
import numpy as np

print("Numpy Version: " + np.__version__)

Numpy Version: 1.18.3


In [297]:
# Exercise 2
n = np.arange(10)

print("n: " + str(n))

n: [0 1 2 3 4 5 6 7 8 9]


In [298]:
# Exercise 3
A = np.full((3, 3), True, dtype=bool)
B = np.ones((3,3), dtype=bool)

print("A: " + str(A) + "\n")
print("B: " + str(B) + "\n")
print("A is equal to B: " + str((A==B).all()))

A: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

B: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

A is equal to B: True


In [299]:
# Exercise 4
n = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Odd Numbers of n: " + str(n[n % 2 == 1]))

Odd Numbers of n: [1 3 5 7 9]


In [300]:
# Exercise 5
n = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
n[n % 2 == 1] = -1

print("n: " + str(n))

n: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [301]:
# Exercise 6
n = np.arange(10)
m = np.where(n % 2 == 1, -1, n)

print("n: " + str(n))
print("m: "+ str(m))

n: [0 1 2 3 4 5 6 7 8 9]
m: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [302]:
# Exercise 7
n = np.arange(10)
n = n.reshape(2, -1)

print("Reshapen to 2D Array, n: " + str(n))

Reshapen to 2D Array, n: [[0 1 2 3 4]
 [5 6 7 8 9]]


In [303]:
# Exercise 8
A = np.arange(10).reshape(2,-1)
B = np.repeat(1, 10).reshape(2,-1)

C = np.concatenate([A,B], axis=0)
D = np.vstack([A, B])

print("A:" + str(A) + "\n")
print("B: " + str(B)+ "\n")
print("C: " + str(C) + "\n")
print("Result Comparison: " + str((C==D).all()))

A:[[0 1 2 3 4]
 [5 6 7 8 9]]

B: [[1 1 1 1 1]
 [1 1 1 1 1]]

C: [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Result Comparison: True


In [304]:
#Exercise 9
A = np.arange(10).reshape(2,-1)
B = np.repeat(1, 10).reshape(2,-1)

C = np.concatenate([A,B], axis=1)
D = np.hstack([A, B])

print("A:" + str(A) + "\n")
print("B: " + str(B)+ "\n")
print("C: " + str(C) + "\n")
print("Result Comparison: " + str((C==D).all()))

A:[[0 1 2 3 4]
 [5 6 7 8 9]]

B: [[1 1 1 1 1]
 [1 1 1 1 1]]

C: [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]

Result Comparison: True


In [305]:
# Exercise 10
A = np.array([1,2,3])
B = np.r_[np.repeat(A, 3), np.tile(A, 3)]

print("A: " + str(A))
print("B: " + str(B))

A: [1 2 3]
B: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [306]:
# Exercise 11
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

C = np.intersect1d(A,B)

print("A: " + str(A))
print("B: " + str(B))
print("Common Items: " + str(C))

A: [1 2 3 2 3 4 3 4 5 6]
B: [ 7  2 10  2  7  4  9  4  9  8]
Common Items: [2 4]


In [307]:
# Exercise 12
A = np.array([1,2,3,4,5])
B = np.array([5,6,7,8,9])

C = np.setdiff1d(A,B)

print("A: " + str(A))
print("B: " + str(B))
print("Items not in B but in A: " + str(C))

A: [1 2 3 4 5]
B: [5 6 7 8 9]
Items not in B but in A: [1 2 3 4]


In [308]:
# Exercise 13
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

C = np.where(A==B)

print("A: " + str(A))
print("B: " + str(B))
print("Indices of matching Items: " + str(C))

A: [1 2 3 2 3 4 3 4 5 6]
B: [ 7  2 10  2  7  4  9  4  9  8]
Indices of matching Items: (array([1, 3, 5, 7], dtype=int64),)


In [309]:
# Exercise 14
A = np.array([2, 6, 1, 9, 10, 3, 27])
B = A[(A >= 5) & (A <= 10)]

print("A: "+ str(A))
print("B: "+ str(B))

A: [ 2  6  1  9 10  3 27]
B: [ 6  9 10]


In [310]:
# Exercise 15
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

A = np.array([5, 7, 9, 8, 6, 4, 5])
B = np.array([6, 3, 4, 8, 9, 7, 1])

C = pair_max(A, B)

print("A: " + str(A))
print("B: " + str(B))
print("Always max of A and B: " + str(C))

A: [5 7 9 8 6 4 5]
B: [6 3 4 8 9 7 1]
Always max of A and B: [6. 7. 9. 8. 9. 7. 5.]


In [311]:
# Exercise 16
A = np.arange(9).reshape(3,3)
B = A[:, [1,0,2]]

print("A: " + str(A) + "\n")
print("B: " + str(B))

A: [[0 1 2]
 [3 4 5]
 [6 7 8]]

B: [[1 0 2]
 [4 3 5]
 [7 6 8]]


In [312]:
# Exercise 17
A = np.arange(9).reshape(3,3)
B = A[[1,0,2], :]

print("A: " + str(A) + "\n")
print("B: " + str(B))

A: [[0 1 2]
 [3 4 5]
 [6 7 8]]

B: [[3 4 5]
 [0 1 2]
 [6 7 8]]


In [313]:
# Exercise 18
A = np.arange(9).reshape(3,3)
B = A[::-1]

print("A: " + str(A) + "\n")
print("B: " + str(B))

A: [[0 1 2]
 [3 4 5]
 [6 7 8]]

B: [[6 7 8]
 [3 4 5]
 [0 1 2]]


In [314]:
# Exercise 19
A = np.arange(9).reshape(3,3)
B = A[:, ::-1]

print("A: " + str(A) + "\n")
print("B: " + str(B))

A: [[0 1 2]
 [3 4 5]
 [6 7 8]]

B: [[2 1 0]
 [5 4 3]
 [8 7 6]]


In [315]:
# Exercise 20
A = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
B = np.random.uniform(5,10, size=(5,3))

print("A: " + str(A) + "\n")
print("B: " + str(B))

A: [[5.632384 9.699359 8.641965]
 [9.920024 7.298876 5.568746]
 [8.178624 6.532574 7.646691]
 [8.142065 9.581389 9.47919 ]
 [6.386419 8.440465 9.404757]]

B: [[7.21127  5.150616 8.880027]
 [7.754792 6.905367 7.646329]
 [9.784385 5.879107 5.591514]
 [9.314728 5.374334 9.125474]
 [9.180659 5.376975 5.057004]]


In [316]:
# Exercise 21
A = np.random.uniform(5,10, size=(5,3))

np.set_printoptions(precision=3)
print("A: " + str(A))

A: [[5.242 6.786 8.328]
 [5.057 5.54  9.505]
 [8.974 9.057 8.201]
 [8.124 5.728 7.851]
 [5.326 6.567 6.085]]


In [317]:
# Exercise 22
np.set_printoptions(suppress=False) # Default
np.random.seed(100)
A = np.random.random([3,3])/1e3

np.set_printoptions(suppress=True, precision=6)
print("A: " + str(A))

A: [[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [318]:
# Exercise 23
A = np.arange(15)

np.set_printoptions(threshold=6)
print("A: " + str(A))

A: [ 0  1  2 ... 12 13 14]


In [319]:
# Exercise 24
np.set_printoptions(threshold=6)     # Truncate like Exercise 23
A = np.arange(15)
print("Truncated A: " + str(A))

np.set_printoptions(threshold=sys.maxsize)
print("Untruncated A: " + str(A))

Truncated A: [ 0  1  2 ... 12 13 14]
Untruncated A: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [320]:
# Exercise 25
URL = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
A = np.genfromtxt(URL, delimiter=',', dtype='object')
Names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

print("A: " + str(A))

A: [[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b

In [321]:
# Round Up
print("I read the first X (X<=25) exersises! ;)")

I read the first X (X<=25) exersises! ;)


In [322]:
# Pandas Exercise

In [323]:
# Setup
import pandas as pd

URL = "https://raw.githubusercontent.com/edlich/eternalrepo/master/DS-WAHLFACH/countries.csv"
data = pd.read_csv(URL)

In [324]:
# Display Basic Statistical Info of the Dataset
print("Data Info:\n" + str(data.info()) + "\n")
print("Data General Calculations:\n" + str(data.describe()))
data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Name      5 non-null      object
 1   People    5 non-null      int64 
 2   Area      5 non-null      int64 
 3   BIP       5 non-null      int64 
 4   Currency  5 non-null      object
dtypes: int64(3), object(2)
memory usage: 328.0+ bytes
Data Info:
None

Data General Calculations:
             People          Area         BIP
count  5.000000e+00  5.000000e+00     5.00000
mean   1.027863e+08  3.907400e+06  2716.20000
std    6.759970e+07  4.904957e+06  1457.86083
min    3.650310e+07  3.013380e+05  1529.00000
25%    6.050172e+07  3.573850e+05  1798.00000
50%    8.252165e+07  3.778350e+05  1850.00000
75%    1.260450e+08  8.515770e+06  3466.00000
max    2.083600e+08  9.984670e+06  4938.00000


Name     People     Area   BIP Currency
0   Germany   82521653   357385  3466      EUR
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL

In [325]:
# Show the last 4 rows of the Dataset
if len(data.index) >= 4:
    print("Last 4 rows:\n" + str(data[-4:]))
else:
    print("Less than 4 rows in the DataSet")

Last 4 rows:
       Name     People     Area   BIP Currency
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL


In [326]:
# Show all the row of countries who have the EURO
data[data["Currency"] == "EUR"]

Name    People    Area   BIP Currency
0  Germany  82521653  357385  3466      EUR
3    Italy  60501718  301338  1850      EUR

In [327]:
# Show only name and Currency in a new data frame
A = data[["Name", "Currency"]]
A

Name Currency
0   Germany      EUR
1     Japan      YEN
2    Canada      CAD
3     Italy      EUR
4  Brazilia     REAL

In [328]:
# Show only the rows/countries that have more than 2000 BIP
data[data["BIP"] > 2000]

Name     People    Area   BIP Currency
0  Germany   82521653  357385  3466      EUR
1    Japan  126045000  377835  4938      YEN

In [329]:
# Select all countries with inhabitants between 50 and 150 Mio
X = data["People"]
data[(X > 50e6) & (X < 150e6)]

Name     People    Area   BIP Currency
0  Germany   82521653  357385  3466      EUR
1    Japan  126045000  377835  4938      YEN
3    Italy   60501718  301338  1850      EUR

In [330]:
# Change BIP to Bip
A = data.rename(columns={"BIP": "Bip"})
A

Name     People     Area   Bip Currency
0   Germany   82521653   357385  3466      EUR
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL

In [331]:
# Calculate the Bip sum
A["Bip"].sum()

13581

In [332]:
# Calculate the average people of all countries
A["People"].mean()

102786293.6

In [333]:
# Sort by name alphabetically
A.sort_values(["Name"])

Name     People     Area   Bip Currency
4  Brazilia  208360000  8515770  1798     REAL
2    Canada   36503097  9984670  1529      CAD
0   Germany   82521653   357385  3466      EUR
3     Italy   60501718   301338  1850      EUR
1     Japan  126045000   377835  4938      YEN

In [334]:
# Create a new data frame from the original where the area is changed as follows: all countries with > 1000000 get BIG and <= 1000000 get SMALL in the cell replaced!
def replace(x):
    if x > 1000000:
        return "BIG"
    else:
        return "SMALL"

B = data.copy()
B["Area"] = B.apply(lambda x: replace(x["Area"]), axis=1)
B

Name     People   Area   BIP Currency
0   Germany   82521653  SMALL  3466      EUR
1     Japan  126045000  SMALL  4938      YEN
2    Canada   36503097    BIG  1529      CAD
3     Italy   60501718  SMALL  1850      EUR
4  Brazilia  208360000    BIG  1798     REAL